# Generated by Django 4.2 on 2023-05-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Texte',
            new_name='Text',
        ),
    ]
